# domains/kitting/fixture_two_tables.py
"""
env_layout8 and scenario_80 / scenario_81: the two-table fixture for B3.B
(T-B1b; design_decisions.md, "B3.B ... THE FIXTURE SIDE"). Generated and
registered programmatically (fixture_generation.py, TODO-47 (a)).

env_layout1's room (2000 x 1000 cm) and its eight shelf positions, with two
kitting tables far apart and six items. No coffee machine or AC switch, and no
item on shelf_2 / shelf_5: every object of a typed parameter is a hypothesis,
and the fixture is about ordering.

The robot's pool: item_6 and item_1 (short, beside kitting_table_0), item_4
(far east, to kitting_table_0), item_7 (near the robot's start, to
kitting_table_1): three to one table, one to the other. From the robot's start
the cheapest single task is item_6, but the cheapest full ordering starts with
item_7: its delivery ends beside item_4's shelf, whose delivery ends beside the
two short tasks. Single-task selection cannot see that.

scenario_80 (plain cost): the human works the north shelves and uses each table
while the robot is elsewhere. scenario_81 (realized cost): the human starts
further from item_0, so its first task spans the robot's two short tasks and
ends at kitting_table_0 as the second of them does: the conflict is in the
second task of the ordering (item_6, item_1), not in its head.

Regenerate the layout file from the repo root:
    python -m domains.kitting.fixture_two_tables
"""

from domains.kitting.fixture_generation import build_layout, delivery_scenario, register_layout, write_layout

LAYOUT_NAME = "env_layout8"
LAYOUT_PATH = "domains/kitting/env_layout8.json"

ROBOT_START = (-100, -400)
HUMAN_START_80 = (-600, 400)
HUMAN_START_81 = (-300, 200)
ROBOT_ITEMS = ["item_1", "item_6", "item_4", "item_7"]
HUMAN_ITEMS = ["item_0", "item_3"]

layout = build_layout(
    name="Kitting Domain Layout 8",
    notes="Two kitting tables, for B3.B (T-B1b). env_layout1's room and shelf positions. Generated by "
          "domains/kitting/fixture_two_tables.py; do not edit by hand.",
    width=2000,
    height=1000,
    tables={"kitting_table_0": (-700, -250), "kitting_table_1": (700, -50)},
    shelves={"shelf_0": (-950, 400), "shelf_1": (-950, -450), "shelf_2": (-950, 0), "shelf_3": (950, 400),
             "shelf_4": (950, -300), "shelf_5": (950, 0), "shelf_6": (-500, -450), "shelf_7": (300, -450)},
    items={"item_1": ("shelf_1", "kitting_table_0"), "item_6": ("shelf_6", "kitting_table_0"),
           "item_4": ("shelf_4", "kitting_table_0"), "item_7": ("shelf_7", "kitting_table_1"),
           "item_0": ("shelf_0", "kitting_table_0"), "item_3": ("shelf_3", "kitting_table_1")},
    robot_start=ROBOT_START,
    human_start=HUMAN_START_80,
)

scenario_80 = delivery_scenario(
    id="scenario_80",
    name="layout8_two_tables_plain_order",
    description=(
        "Two tables, ordering isolated: the robot's cheapest first task (item_6) is not the head of its "
        "cheapest full ordering (item_7 first). The human works the north shelves, uses both tables and "
        "stays clear of the robot's paths."
    ),
    layout=layout, human_start=HUMAN_START_80, human_items=HUMAN_ITEMS,
    robot_start=ROBOT_START, robot_items=ROBOT_ITEMS,
)

scenario_81 = delivery_scenario(
    id="scenario_81",
    name="layout8_two_tables_conflict_past_head",
    description=(
        "scenario_80 with the human starting further from item_0: its first task spans the robot's two "
        "short tasks and ends at kitting_table_0 as the second of them does, so the conflict falls in the "
        "second task of the ordering (item_6, item_1), not in its head."
    ),
    layout=layout, human_start=HUMAN_START_81, human_items=HUMAN_ITEMS,
    robot_start=ROBOT_START, robot_items=ROBOT_ITEMS,
)


def register(domain_config: dict) -> None:
    register_layout(domain_config, LAYOUT_NAME, LAYOUT_PATH, layout, [scenario_80, scenario_81])


if __name__ == "__main__":
    write_layout(layout, LAYOUT_PATH)
