# domains/kitting/scenarios/scenarios_s103.py
"""
Kitting scenarios on env_setup_103: the demo-day round of T-F (Hadi, 8 October 2026; analysis/kitting/tf_demo/README.md), on env_layout_100. One module per setup. GENERATED by analysis/kitting/tf_demo/generate.py (seed 20261008); not edited by hand, never redrawn after a result.
_01, _02 group a (deliveries only); _03 to _06 group b (one coffee break); _07, _08 group c, the mix (a switch mid-task, a coffee break, an unmodelled behaviour); _09, _10 group c, unmodelled behaviour only.
The robot's and the human's items are disjoint. Every script ends with the exit walk to corner_SE.
Draws discarded by the redraw rule: 0
"""

from shared.types import AgentConfig, ScenarioConfig, Script
from domains.kitting.actions import move_to, pick_up
from domains.kitting.script import deliver_item, coffee_break, go_to, stand, go_to_and_stand


scenario_s103_01 = ScenarioConfig(
    id="scenario_s103_01",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_01: group a: the human does its assigned deliveries only. The robot has 13 deliveries, the human 3; the human's script: nothing besides the deliveries; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_13", table="kitting_table_1"),
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_9", table="kitting_table_1"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_19", table="kitting_table_1"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_11", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_02 = ScenarioConfig(
    id="scenario_s103_02",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_02: group a: the human does its assigned deliveries only. The robot has 10 deliveries, the human 5; the human's script: nothing besides the deliveries; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_13", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_18", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_15", table="kitting_table_1"),
                deliver_item("item_23", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_03 = ScenarioConfig(
    id="scenario_s103_03",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_03: group b: the assigned deliveries and one coffee break. The robot has 9 deliveries, the human 7; the human's script: a coffee break before the exit walk; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                coffee_break("coffee_machine_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_9", table="kitting_table_1"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_19", table="kitting_table_1"),
                deliver_item("item_13", table="kitting_table_1"),
                deliver_item("item_18", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_0"),
                deliver_item("item_15", table="kitting_table_1"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_20", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_04 = ScenarioConfig(
    id="scenario_s103_04",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_04: group b: the assigned deliveries and one coffee break. The robot has 10 deliveries, the human 3; the human's script: a coffee break inside the delivery of item_15, after the carry to the table; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_15", table="kitting_table_1").at(move_to, coffee_break("coffee_machine_1"), occurrence=1),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_0"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_15", table="kitting_table_1"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_13", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_1"),
                deliver_item("item_18", table="kitting_table_0"),
                deliver_item("item_19", table="kitting_table_1"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_7", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_05 = ScenarioConfig(
    id="scenario_s103_05",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_05: group b: the assigned deliveries and one coffee break. The robot has 10 deliveries, the human 4; the human's script: a coffee break before delivery 3; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_10", table="kitting_table_1"),
                deliver_item("item_11", table="kitting_table_1"),
                coffee_break("coffee_machine_1"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_0"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_10", table="kitting_table_1"),
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_19", table="kitting_table_1"),
                deliver_item("item_15", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
                deliver_item("item_13", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_20", table="kitting_table_1"),
                deliver_item("item_9", table="kitting_table_1"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_3", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_06 = ScenarioConfig(
    id="scenario_s103_06",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_06: group b: the assigned deliveries and one coffee break. The robot has 9 deliveries, the human 6; the human's script: a coffee break inside the delivery of item_5, after the walk to the shelf; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1").at(move_to, coffee_break("coffee_machine_1"), occurrence=0),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_9", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_1"),
                deliver_item("item_2", table="kitting_table_0"),
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_15", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_07 = ScenarioConfig(
    id="scenario_s103_07",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_07: group c, the mix: a switch mid-task, a coffee break and an unmodelled behaviour. The robot has 13 deliveries, the human 4; the human's script: the switch from the delivery of item_12 to the delivery of item_17, after the walk to the shelf; item_12's delivery resumes after it; a coffee break inside the delivery of item_3, after the walk to the shelf; a walk to corner_SE and a stand of PT80S there before the exit walk; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_3", table="kitting_table_0").at(move_to, coffee_break("coffee_machine_1"), occurrence=0),
                deliver_item("item_12", table="kitting_table_1").at(move_to, deliver_item("item_17", table="kitting_table_0"), occurrence=0),
                go_to_and_stand("corner_SE", "PT80S"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_17", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_18", table="kitting_table_0"),
                deliver_item("item_15", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_9", table="kitting_table_1"),
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_08 = ScenarioConfig(
    id="scenario_s103_08",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_08: group c, the mix: a switch mid-task, a coffee break and an unmodelled behaviour. The robot has 8 deliveries, the human 3; the human's script: the switch from the delivery of item_23 to the delivery of item_21, after the grasp; item_23's delivery resumes after it; a coffee break before the exit walk; the misdelivery of item_6 to kitting_table_1 (designated kitting_table_0); then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_23", table="kitting_table_1").at(pick_up, deliver_item("item_21", table="kitting_table_1")),
                deliver_item("item_6", table="kitting_table_1"),
                coffee_break("coffee_machine_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_13", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_09 = ScenarioConfig(
    id="scenario_s103_09",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_09: group c, unmodelled behaviour only: two unmodelled behaviours. The robot has 13 deliveries, the human 4; the human's script: a walk to corner_SE and a stand of PT80S there before delivery 4; the misdelivery of item_3 to kitting_table_1 (designated kitting_table_0); then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_19", table="kitting_table_1"),
                deliver_item("item_3", table="kitting_table_1"),
                go_to_and_stand("corner_SE", "PT80S"),
                deliver_item("item_20", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_19", table="kitting_table_1"),
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_20", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_16", table="kitting_table_0"),
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_9", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_1"),
                deliver_item("item_2", table="kitting_table_0"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_1", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s103_10 = ScenarioConfig(
    id="scenario_s103_10",
    setup="env_setup_103",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s103_10: group c, unmodelled behaviour only: two unmodelled behaviours. The robot has 11 deliveries, the human 4; the human's script: a walk to corner_SE and a stand of PT40S there before the exit walk; a walk to corner_SE and a stand of PT120S there before the exit walk; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_18", table="kitting_table_0"),
                go_to_and_stand("corner_SE", "PT40S"),
                go_to_and_stand("corner_SE", "PT120S"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_18", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_13", table="kitting_table_1"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_1"),
                deliver_item("item_9", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_0"),
                deliver_item("item_16", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)
