# domains/kitting/scenarios/scenarios_s104.py
"""
Kitting scenarios on env_setup_104: the demo-day round of T-F (Hadi, 8 October 2026; analysis/kitting/tf_demo/README.md), on env_layout_100. One module per setup. GENERATED by analysis/kitting/tf_demo/generate.py (seed 20261008); not edited by hand, never redrawn after a result.
_01, _02 group a (deliveries only); _03 to _06 group b (one coffee break); _07, _08 group c, the mix (a switch mid-task, a coffee break, an unmodelled behaviour); _09, _10 group c, unmodelled behaviour only.
The robot's and the human's items are disjoint. Every script ends with the exit walk to corner_SE.
Draws discarded by the redraw rule: 1
- scenario_s104_08: Invalid: no free delivery entry
"""

from shared.types import AgentConfig, ScenarioConfig, Script
from domains.kitting.actions import move_to, pick_up
from domains.kitting.script import deliver_item, coffee_break, go_to, stand, go_to_and_stand


scenario_s104_01 = ScenarioConfig(
    id="scenario_s104_01",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_01: group a: the human does its assigned deliveries only. The robot has 9 deliveries, the human 4; the human's script: nothing besides the deliveries; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
                deliver_item("item_18", table="kitting_table_1"),
                deliver_item("item_3", table="kitting_table_0"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
                deliver_item("item_18", table="kitting_table_1"),
                deliver_item("item_3", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_16", table="kitting_table_1"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_9", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_19", table="kitting_table_0"),
                deliver_item("item_6", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_02 = ScenarioConfig(
    id="scenario_s104_02",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_02: group a: the human does its assigned deliveries only. The robot has 8 deliveries, the human 5; the human's script: nothing besides the deliveries; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_18", table="kitting_table_1"),
                deliver_item("item_19", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_18", table="kitting_table_1"),
                deliver_item("item_19", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_16", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_20", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_24", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_03 = ScenarioConfig(
    id="scenario_s104_03",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_03: group b: the assigned deliveries and one coffee break. The robot has 9 deliveries, the human 4; the human's script: a coffee break before delivery 2; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_6", table="kitting_table_0"),
                coffee_break("coffee_machine_1"),
                deliver_item("item_9", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_1"),
                deliver_item("item_1", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_9", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_1"),
                deliver_item("item_1", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
                deliver_item("item_13", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_15", table="kitting_table_0"),
                deliver_item("item_23", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_04 = ScenarioConfig(
    id="scenario_s104_04",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_04: group b: the assigned deliveries and one coffee break. The robot has 8 deliveries, the human 3; the human's script: a coffee break before the exit walk; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
                coffee_break("coffee_machine_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_1"),
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_0"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_16", table="kitting_table_1"),
                deliver_item("item_11", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_05 = ScenarioConfig(
    id="scenario_s104_05",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_05: group b: the assigned deliveries and one coffee break. The robot has 8 deliveries, the human 4; the human's script: a coffee break before delivery 4; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                coffee_break("coffee_machine_1"),
                deliver_item("item_14", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_13", table="kitting_table_0"),
                deliver_item("item_16", table="kitting_table_1"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_3", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_06 = ScenarioConfig(
    id="scenario_s104_06",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_06: group b: the assigned deliveries and one coffee break. The robot has 10 deliveries, the human 6; the human's script: a coffee break before delivery 5; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_1"),
                deliver_item("item_16", table="kitting_table_1"),
                coffee_break("coffee_machine_1"),
                deliver_item("item_15", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_1"),
                deliver_item("item_16", table="kitting_table_1"),
                deliver_item("item_15", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_9", table="kitting_table_0"),
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_4", table="kitting_table_0"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_20", table="kitting_table_1"),
                deliver_item("item_19", table="kitting_table_0"),
                deliver_item("item_17", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_07 = ScenarioConfig(
    id="scenario_s104_07",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_07: group c, the mix: a switch mid-task, a coffee break and an unmodelled behaviour. The robot has 12 deliveries, the human 6; the human's script: the switch from the delivery of item_22 to the delivery of item_17, after the grasp; item_22's delivery resumes after it; a coffee break before delivery 3; the misdelivery of item_24 to kitting_table_1 (designated kitting_table_0); then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                coffee_break("coffee_machine_1"),
                deliver_item("item_24", table="kitting_table_1"),
                deliver_item("item_22", table="kitting_table_1").at(pick_up, deliver_item("item_17", table="kitting_table_0")),
                deliver_item("item_11", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_11", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_8", table="kitting_table_0"),
                deliver_item("item_15", table="kitting_table_0"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_0"),
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_13", table="kitting_table_0"),
                deliver_item("item_9", table="kitting_table_0"),
                deliver_item("item_18", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_08 = ScenarioConfig(
    id="scenario_s104_08",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_08: group c, the mix: a switch mid-task, a coffee break and an unmodelled behaviour. The robot has 10 deliveries, the human 7; the human's script: the switch from the delivery of item_23 to the delivery of item_6, after the grasp; item_23's delivery resumes after it; a coffee break before the exit walk; the misdelivery of item_12 to kitting_table_0 (designated kitting_table_1); then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_10", table="kitting_table_0"),
                deliver_item("item_15", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_0"),
                deliver_item("item_23", table="kitting_table_1").at(pick_up, deliver_item("item_6", table="kitting_table_0")),
                deliver_item("item_4", table="kitting_table_0"),
                coffee_break("coffee_machine_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_10", table="kitting_table_0"),
                deliver_item("item_15", table="kitting_table_0"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_4", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_5", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_20", table="kitting_table_1"),
                deliver_item("item_16", table="kitting_table_1"),
                deliver_item("item_11", table="kitting_table_1"),
                deliver_item("item_1", table="kitting_table_1"),
                deliver_item("item_13", table="kitting_table_0"),
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_9", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_09 = ScenarioConfig(
    id="scenario_s104_09",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_09: group c, unmodelled behaviour only: two unmodelled behaviours. The robot has 9 deliveries, the human 4; the human's script: a stand of PT40S inside the delivery of item_6, after the walk to the shelf; the misdelivery of item_17 to kitting_table_1 (designated kitting_table_0); then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_17", table="kitting_table_1"),
                deliver_item("item_6", table="kitting_table_0").at(move_to, stand("PT40S"), occurrence=0),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_1", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_17", table="kitting_table_0"),
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_1", table="kitting_table_1"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_22", table="kitting_table_1"),
                deliver_item("item_14", table="kitting_table_1"),
                deliver_item("item_10", table="kitting_table_0"),
                deliver_item("item_23", table="kitting_table_1"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_18", table="kitting_table_1"),
                deliver_item("item_20", table="kitting_table_1"),
            ],
            observes=["human_0"],
        ),
    ],
)


scenario_s104_10 = ScenarioConfig(
    id="scenario_s104_10",
    setup="env_setup_104",
    reference_layouts=["env_layout_100"],
    description=(
        "scenario_s104_10: group c, unmodelled behaviour only: two unmodelled behaviours. The robot has 10 deliveries, the human 4; the human's script: the misdelivery of item_8 to kitting_table_1 (designated kitting_table_0); a walk to corner_SE and a stand of PT80S there inside the delivery of item_6, after the carry to the table; then the exit walk. Generated by analysis/kitting/tf_demo/generate.py (seed 20261008)."
    ),
    agents=[
        AgentConfig(
            agent_id="human_0",
            agent_type="human",
            start_position=(5, 380),
            scheduled_tasks=Script([
                deliver_item("item_6", table="kitting_table_0").at(move_to, go_to_and_stand("corner_SE", "PT80S"), occurrence=1),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_19", table="kitting_table_0"),
                deliver_item("item_8", table="kitting_table_1"),
                go_to("corner_SE"),
            ]),
            assigned_tasks=[
                deliver_item("item_6", table="kitting_table_0"),
                deliver_item("item_21", table="kitting_table_1"),
                deliver_item("item_19", table="kitting_table_0"),
                deliver_item("item_8", table="kitting_table_0"),
            ],
            observes=[],
        ),
        AgentConfig(
            agent_id="robot_0",
            agent_type="robot",
            start_position=(0, -380),
            assigned_tasks=[
                deliver_item("item_3", table="kitting_table_0"),
                deliver_item("item_10", table="kitting_table_0"),
                deliver_item("item_12", table="kitting_table_1"),
                deliver_item("item_7", table="kitting_table_0"),
                deliver_item("item_14", table="kitting_table_1"),
                deliver_item("item_18", table="kitting_table_1"),
                deliver_item("item_2", table="kitting_table_1"),
                deliver_item("item_9", table="kitting_table_0"),
                deliver_item("item_24", table="kitting_table_0"),
                deliver_item("item_17", table="kitting_table_0"),
            ],
            observes=["human_0"],
        ),
    ],
)
