#!/usr/bin/env python3
"""
blocked.py — blocked time and human-borne proximity as outcomes, from the logs alone (R2).

Usage (repo root):
    python analysis/c_separation_stop/blocked.py [dir ...] > analysis/c_separation_stop/blocked.md

Reads every <dir>/<cond>.log (default: stop_off/ and stop_on/, the C runs) and reports per run:
  - BLOCKED TIME, from the executor's [stop] lines: total blocked ticks, the episodes (contiguous
    ticks), and per episode the action and the place it was walking to. Completion is reported only
    when the run completes ([meta] ... all tasks complete); otherwise the run is "blocked by an
    occupying human" when its last stop episode runs to the step cap (with the blocked duration), or
    "not completed within the cap" when it does not.
  - HUMAN-BORNE PROXIMITY: ticks on which the robot did not move (the F1 evaluation's "stand" label)
    and the tick-sampled distance is below min_separation, split by what the robot was doing — a
    separation stop, a decided hold, its own stationary action (grasp / release / wait), or standing
    idle after its last task ("done"). Reported next to the ROBOT VIOLATIONS of the F1 rule on Mesa's
    sequential motion (evaluate.py's acceptance check), so that the two sides of one close moment are
    on one line: what the robot did, what the human did.
  - FOR D2: stops per blocked place (ticks and episodes), and the robot's walks — a walk is a maximal
    run of ticks executing one move_to — with how many contain a stop and how many END in one (the
    walk never resumed before the cap).
Only the line formats of run_mesa.py / meta_planner.py / executor.py are read (analysis/logparse.py); no simulator import.
"""
import sys
from pathlib import Path

HERE = Path(__file__).parent
sys.path.insert(0, str(HERE.parent))
import logparse
from logparse import episodes
SEP = 50.0
DIRS = [Path(a) for a in sys.argv[1:]] or [HERE / "stop_off", HERE / "stop_on"]

def parse(path):
    run = logparse.parse(path)
    run["done"] = run["declared"]
    return run

def sequential_violations(run):
    """evaluate.py's acceptance check: ticks on which the robot moved and its step broke the F1 rule."""
    return [k for k, _, _ in logparse.sequential_violations(run, SEP)]

def stand_within(run):
    """Ticks on which the robot did not move and the sampled distance is below SEP, by what it was doing."""
    stop_ticks = {d["step"] for d in run["stops"]}
    out = {"stop": [], "hold": [], "own_action": [], "done": []}
    for k in sorted(run["sep"]):
        if k - 1 not in run["rpos"] or k not in run["rpos"]: continue
        if run["rpos"][k] != run["rpos"][k - 1] or run["sep"][k][0] >= SEP: continue
        if k in stop_ticks: out["stop"].append(k)
        elif k in run["hold_ticks"]: out["hold"].append(k)
        elif run["done"] is not None and k >= run["done"]: out["done"].append(k)
        else: out["own_action"].append(k)
    return out

def walks(run):
    """Maximal runs of ticks executing one move_to (the robot's own task in flight)."""
    ticks = [k for k in sorted(run["ract"]) if run["ract"][k] == "move_to" and run["rtask"][k] != "None"]
    return episodes(ticks)

def fmt_eps(eps): return "; ".join(f"{e[0]}–{e[-1]} ({len(e)})" for e in eps) or "none"

runs = {d.name: {p.stem: parse(p) for p in sorted(d.glob("*.log"))} for d in DIRS}

print("# Blocked time and human-borne proximity (R2)\n")
print(f"Generated by `blocked.py` over {', '.join(d.name for d in DIRS)}. min_separation {SEP:g} cm; "
      "PYTHONHASHSEED=0. Blocked ticks are the executor's [stop] refusals; \"stand < s\" ticks are those on "
      "which the robot did not move and the sampled distance was below min_separation (the human's side of "
      "a close moment: a separation stop, a decided hold, the robot's own grasp / release / wait, or standing "
      "idle after its last task); robot violations are evaluate.py's acceptance count (the F1 rule on the "
      "robot's own steps, sequential motion).\n")

for dname, conds in runs.items():
    print(f"## {dname}\n")
    print("| run | outcome | blocked ticks | stop episodes (place) | robot violations | stand < s: stop / hold / own action / done | walks | with a stop | ending in a stop |")
    print("|---|---|---|---|---|---|---|---|---|")
    for c, run in conds.items():
        st = run["stops"]; ticks = [d["step"] for d in st]; eps = episodes(ticks)
        by_tick = {d["step"]: d for d in st}
        last = run["steps"] - 1
        if run["done"] is not None:
            outcome = f"completed at {run['done']}"
        elif eps and eps[-1][-1] == last:
            e = eps[-1]; d = by_tick[e[0]]
            outcome = f"blocked by an occupying human: {d['action']} to {d['place']} refused {len(e)} ticks ({e[0]}–{last})"
        else:
            outcome = f"not completed within {run['steps']}"
        ep_s = "; ".join(f"{e[0]}–{e[-1]} ({len(e)}, {by_tick[e[0]]['action']}→{by_tick[e[0]]['place']})" for e in eps) or "none"
        sw = stand_within(run)
        ws = walks(run)
        stop_set = set(ticks)
        with_stop = sum(1 for w in ws if stop_set & set(w))
        end_stop = sum(1 for w in ws if w[-1] in stop_set)
        viol = sequential_violations(run)
        print(f"| {c} | {outcome} | {len(ticks)} | {ep_s} | {len(viol)}"
              + (f" ({', '.join(map(str, viol))})" if viol else "")
              + f" | {len(sw['stop'])} / {len(sw['hold'])} / {len(sw['own_action'])} / {len(sw['done'])} | {len(ws)} | {with_stop} | {end_stop} |")
    print()
    # Per-place table for D2.
    places = {}
    for c, run in conds.items():
        for e in episodes([d["step"] for d in run["stops"]]):
            d = next(x for x in run["stops"] if x["step"] == e[0])
            key = (c, d["place"])
            places.setdefault(key, [0, 0]); places[key][0] += len(e); places[key][1] += 1
    if places:
        print("Stops per blocked place (ticks, episodes):\n")
        print("| run | place | blocked ticks | episodes |")
        print("|---|---|---|---|")
        for (c, place), (t, n) in sorted(places.items()):
            print(f"| {c} | {place} | {t} | {n} |")
        print()
    # Detail of the stand-within ticks, so the human-borne moments are locatable.
    print("Stand < s ticks (episodes):\n")
    for c, run in conds.items():
        sw = stand_within(run)
        parts = [f"{k} {fmt_eps(episodes(v))}" for k, v in sw.items() if v]
        print(f"- {c}: " + ("; ".join(parts) if parts else "none"))
    print()
